[package]
name = "mctc-parser"
version = "0.1.0"
edition = "2021"

[dependencies]
bitflags = "2.9.1"
criterion = "0.6.0"
paste = "1.0.15"
rand = "0.9.0"

[features]
io = []

[[bench]]
name = "decode"
harness = false
