[package]
name = "mctc-parser"
version = "0.1.0"
edition = "2021"

[dependencies]
ascii = "1.1.0"
bitflags = "2.6.0"
criterion = "0.5.1"
rand = "0.9.0"

[features]
io = []

[[bench]]
name = "decode"
harness = false
